language: ruby

rvm:
  - 2.4.5
  - 2.5.0
  - 2.5.1
  - 2.5.2
  - 2.5.3

sudo: false

env:
  matrix:
    - HANDLER="nokogiri"
    - HANDLER="ox"
    - HANDLER="oga"

notifications:
  webhooks:
    secure: QFW4WHH8A/ht3EKFbUNc7u03Ca+P6qm7ypIiXU+y8fO8fEps2/f7fTrWIUGkohShFyaaZw1/NjDWUx86LYBFfs4dYduHy8U3BSbWrS4ot4+oO9TsKdatKydTXpbvRqjgPITECmMWDoz4e7gMdZ5fGuBBdO1LQGVRr9mUXl13QU4=
