language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - jruby-1.7
  - rbx-2
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
    - env: PARSER="ox"
      rvm: jruby-1.7
    - env: PARSER="ox"
      rvm: jruby-head
env:
  matrix:
    - PARSER="nokogiri"
    - PARSER="ox"
