language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - jruby-1.7
  - rbx-2
  - ruby-head
  - jruby-head
matrix:
  exclude:
    - env: HANDLER="ox"
      rvm: jruby-1.7
    - env: HANDLER="ox"
      rvm: jruby-head
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
env:
  matrix:
    - HANDLER="nokogiri"
    - HANDLER="ox"
    - HANDLER="oga"
